name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  background_sms: ^0.0.4
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.0
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.0.1
  flutter_background_service_ios: ^5.0.0
  flutter_local_notifications: ^15.1.1
  flutter_phone_direct_caller: ^2.1.1
  fluttertoast: ^8.2.2
  geocoding: ^2.1.0
  geolocator: ^10.0.0
  google_fonts: ^5.1.0
  image_picker: ^1.0.4
  permission_handler: ^10.4.3
  provider: ^6.0.5
  shake: ^2.2.0
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  telephony: ^0.2.0
  url_launcher: ^6.1.12
  uuid: ^4.0.0
  vibration: ^1.8.1
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/alert.png
    - assets/ambulance.png
    - assets/army.png
    - assets/bus-stop.png
    - assets/flame.png
    - assets/hospital.png
    - assets/pharmacy.png
    - assets/police-badge.png
    - assets/travel.png
    - assets/user.png
    - assets/add_pic.png
